# name: Test and coverage

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: '1.20'
#       - name: Run coverage
#         run: CGO_ENABLED=1 go test ./... -race -covermode=atomic -coverprofile=coverage.out
#       - name: Upload coverage to Codecov
#         uses: codecov/codecov-action@v3

name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run tests and generate coverage report
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o=coverage.html

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      
      - name: Add Codecov Badge to README
        run: |
          echo "[![Codecov](https://codecov.io/gh/louismomo/scraper_go/branch/work_space/graph/badge.svg)](https://codecov.io/gh/louismomo66/work_space)" >> README.md
        shell: bash


