name: Lint Go Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: "false"
          go-version: "1.18"

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2

          golangci-lint run  -c .golangci.yml
      
      - name: test coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o=coverage.html
      
      - name: report
        uses: codecov/codecov-action@v2
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Add Codecov Badge to README
        run: |
          echo "[![Codecov](https://codecov.io/gh/louismomo66/scraper_go/branch/work_space/graph/badge.svg)](https://codecov.io/gh/louismomo/work_space)" >> README.md
        shell: bash